### ISSUE TITLE
[Ye et al., 2023] link leads to benchmark with 16 datasets, not 2000

### ISSUE THREAD

**Issue by dev-rinchin** [wwweiwei/awesome-self-supervised-learning-for-tabular-data#2]
https://github.com/wwweiwei/awesome-self-supervised-learning-for-tabular-data/blob/10dfb11485eba71352da8159b928760028161614/README.md?plain=1#L73

**Comment by wywyWang** [comment]
Hi,

Thanks for your interest in our work. You can download the datasets from [the TP-BERTa repo](https://github.com/jyansir/tp-berta?tab=readme-ov-file#:~:text=Sort%20and%20update%20experiment%20datasets.), which is also from TabPertNet.
